on:
#  pull_request:
#    branches: [main]
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package

    - uses: actions/upload-artifact@v4
      with:
        name: verademo.war
        path: target/verademo.war
        
  pipeline_scan:
      needs: build
      runs-on: ubuntu-latest
      name: pipeline scan
      steps:
        - name: Background timer notifier
          run: |
              (
                i=0
                while true; do
                  i=$((i+1))
                  curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/issues/1/comments \
                    -d "{\"body\":\"⏱️ Job running for $((i * 0.5)) minutes...\"}"
                  sleep 30
                done
              ) &
        - name: checkout repo
          uses: actions/checkout@v3

        - name: get archive
          uses: actions/download-artifact@v4
          with:
            name: verademo.war
        - name: pipeline-scan action step
          id: pipelien-scan
          uses: veracode/Veracode-pipeline-scan-action@v1.0.18
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            #file: "auth.js.zip"
            file: "verademo.war" 
            request_policy: "VeraDemo Policy"
            #store_baseline_file: true
            #store_baseline_file_branch: "feature-123"
            #create_baseline_from: "standard"
            debug: 1
            fail_build: false
