on:
  pull_request:
    branches: [main]

jobs:

  pipeline_scan:
      runs-on: ubuntu-latest
      name: pipeline scan

      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: pipeline-scan action step
          id: pipelien-scan
          uses: julz0815/Veracode-pipeline-scan-action@beta
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            file: "verademo.war" 
            request_policy: "VeraDemo Policy"
            store_baseline_file: true
            store_baseline_file_branch: "feature-123"
            create_baseline_from: "standard"
            debug: 1
            fail_build: true
            
        - name: save filtered results
          uses: actions/upload-artifact@v1
          with:
            name: filtered-results
            path: filtered_results.json
