on:
  pull_request:
    branches: [main]
  
jobs:
  pipeline_scan:
      runs-on: ubuntu-latest
      name: pipeline scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v3
        - name: pipeline-scan action step
          id: pipelien-scan
          uses: veracode/Veracode-pipeline-scan-action@v1.0.1
          #julz0815/Veracode-pipeline-scan-action@beta-0.29
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            file: "helloworld-2.0.jar" 
            request_policy: "VeraDemo Policy"
            debug: 1
            fail_build: false
