on:
  push:
    branches: [feature-123]



jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false 
          fail-on-cvss: 1   
