on:
  pull_request:
    branches: [main]
  workflow_dispatch:



jobs:
        
  pipeline_scan:
      runs-on: ubuntu-latest
      name: pipeline scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v3

        - name: pipeline-scan action step
          id: pipelien-scan
          uses: veracode/Veracode-pipeline-scan-action@v1.0.12
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            file: "target/verademo.war" 
            request_policy: "VeraDemo Policy"
            debug: 0
            fail_build: false

  veracode-fix:
    needs: pipeline_scan
    runs-on: ubuntu-latest
    name: create fixs
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
          
      - name: get flaw file
        uses: actions/download-artifact@v2
        with:
          name: Veracode Pipeline-Scan Results
      - name: Create fixes from static findings
        id: convert
        uses: Veracode/veracode-fix@main
        with:
          file: results.json
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          source_base_path_1: "com/:src/main/java/com/"
          source_base_path_2: "WEB-INF:src/main/webapp/WEB-INF"
          debug: true
