on:
  pull_request:
    branches: [main]
  workflow_dispatch:



jobs:
  veracode-fix:
    runs-on: ubuntu-latest
    name: create fixes
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
          
      - name: Create fixes from static findings
        id: convert
        uses: Veracode/veracode-fix@main
        with:
          inputFile: results.json
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          source_base_path_1: "com/:src/main/java/com/"
          source_base_path_2: "WEB-INF:src/main/webapp/WEB-INF"
          language: java
          debug: true
